In [0]:
import numpy as  np

In [0]:
student_score = [
 [1, 90, 80, 85, 0, 0.0, 0],
 [2, 90, 85, 90, 0, 0.0, 0],
 [3, 80, 80, 80, 0, 0.0, 0]
]
a = [
{'num':'1', 'name':'김철수','kor':90, 'eng':80, 'math':85, 'total':0, 'avg':0.0, 'order':0 },
{'num':'2', 'name':'박제동','kor':90, 'eng':85, 'math':90, 'total':0, 'avg':0.0, 'order':0 },
{'num':'3', 'name':'홍길동','kor':80,' eng':80, 'math':80, 'total':0, 'avg':0.0, 'order':0 }
]

In [0]:
student_scores_high = np.random.randint(low = 80, high=100, size =(30, 3)) 
student_scores_middle = np.random.randint(low = 50, high=79, size =(20, 3)) 
student_scores_low = np.random.randint(low = 0, high=49, size =(100, 3)) 
student_scores_high

In [0]:
student_scores=np.insert(student_scores_high, 0, student_scores_low, axis=0)

In [0]:
student_scores_total=np.insert(student_scores, 0, student_scores_middle, axis=0)
print(student_scores_total)

In [0]:
len(student_scores_total)

150

In [0]:
np.mean(student_scores_total,axis=0), np.median(student_scores_total,axis=0), np.std(student_scores_total,axis=0), np.mean(student_scores_total) #axis가 없으면 전체 개체의 평균을 다 구해줌

(array([43.70666667, 41.14      , 41.97333333]),
 array([37., 34., 34.]),
 array([28.20178403, 30.73955758, 29.74288636]),
 42.27333333333333)

In [0]:
person_mean=np.mean(student_scores_total,axis=1)    
person_std=np.std(student_scores_total,axis=1)      
type(person_mean), type(person_std), len(person_mean), len(person_std)

(numpy.ndarray, numpy.ndarray, 150, 150)

In [0]:
## 구성원별 특징을 보여주는 대표값 선정
#구성원 i의 전과목 평균 성취도를 알기 위해 평균을 사용 
print(person_mean)

[57.         60.         66.66666667 64.         64.66666667 58.66666667
 61.         65.         69.33333333 60.33333333 65.33333333 68.66666667
 59.33333333 59.33333333 71.         63.         72.66666667 66.
 67.         70.33333333 19.33333333 18.33333333 30.         21.
 14.66666667 28.33333333 31.66666667 21.         26.33333333 11.
 30.33333333 22.66666667 20.33333333 27.66666667 36.66666667 27.
 20.66666667 17.66666667 20.33333333 25.33333333 34.33333333 29.
 24.66666667 36.33333333 17.         38.66666667 27.66666667 35.33333333
 22.         37.66666667 13.         15.33333333 30.66666667 39.
 33.66666667 15.66666667 22.33333333 19.         14.33333333 25.66666667
 17.66666667 31.         22.66666667 24.         34.33333333 35.66666667
 29.33333333 25.66666667 22.33333333 15.         23.         14.
 21.         22.         16.66666667 21.         26.33333333 27.
 20.66666667 32.         25.66666667 24.         12.         13.33333333
 19.66666667 14.         25.33333333 41.66

In [0]:
person_mean_list=list(person_mean)

In [0]:
print(person_mean_list)

[57.0, 60.0, 66.66666666666667, 64.0, 64.66666666666667, 58.666666666666664, 61.0, 65.0, 69.33333333333333, 60.333333333333336, 65.33333333333333, 68.66666666666667, 59.333333333333336, 59.333333333333336, 71.0, 63.0, 72.66666666666667, 66.0, 67.0, 70.33333333333333, 19.333333333333332, 18.333333333333332, 30.0, 21.0, 14.666666666666666, 28.333333333333332, 31.666666666666668, 21.0, 26.333333333333332, 11.0, 30.333333333333332, 22.666666666666668, 20.333333333333332, 27.666666666666668, 36.666666666666664, 27.0, 20.666666666666668, 17.666666666666668, 20.333333333333332, 25.333333333333332, 34.333333333333336, 29.0, 24.666666666666668, 36.333333333333336, 17.0, 38.666666666666664, 27.666666666666668, 35.333333333333336, 22.0, 37.666666666666664, 13.0, 15.333333333333334, 30.666666666666668, 39.0, 33.666666666666664, 15.666666666666666, 22.333333333333332, 19.0, 14.333333333333334, 25.666666666666668, 17.666666666666668, 31.0, 22.666666666666668, 24.0, 34.333333333333336, 35.66666666666

In [0]:
i=0
for i in range(len(person_mean_list)):
  print("본 피평가자의 전과목 평균은", person_mean_list[i])
  i=i+1

본 피평가자의 전과목 평균은 57.0
본 피평가자의 전과목 평균은 60.0
본 피평가자의 전과목 평균은 66.66666666666667
본 피평가자의 전과목 평균은 64.0
본 피평가자의 전과목 평균은 64.66666666666667
본 피평가자의 전과목 평균은 58.666666666666664
본 피평가자의 전과목 평균은 61.0
본 피평가자의 전과목 평균은 65.0
본 피평가자의 전과목 평균은 69.33333333333333
본 피평가자의 전과목 평균은 60.333333333333336
본 피평가자의 전과목 평균은 65.33333333333333
본 피평가자의 전과목 평균은 68.66666666666667
본 피평가자의 전과목 평균은 59.333333333333336
본 피평가자의 전과목 평균은 59.333333333333336
본 피평가자의 전과목 평균은 71.0
본 피평가자의 전과목 평균은 63.0
본 피평가자의 전과목 평균은 72.66666666666667
본 피평가자의 전과목 평균은 66.0
본 피평가자의 전과목 평균은 67.0
본 피평가자의 전과목 평균은 70.33333333333333
본 피평가자의 전과목 평균은 19.333333333333332
본 피평가자의 전과목 평균은 18.333333333333332
본 피평가자의 전과목 평균은 30.0
본 피평가자의 전과목 평균은 21.0
본 피평가자의 전과목 평균은 14.666666666666666
본 피평가자의 전과목 평균은 28.333333333333332
본 피평가자의 전과목 평균은 31.666666666666668
본 피평가자의 전과목 평균은 21.0
본 피평가자의 전과목 평균은 26.333333333333332
본 피평가자의 전과목 평균은 11.0
본 피평가자의 전과목 평균은 30.333333333333332
본 피평가자의 전과목 평균은 22.666666666666668
본 피평가자의 전과목 평균은 20.333333333333332
본 피평가자의 전과목 평균은 27.666666666666668

In [0]:
#구성원 i가 각 과목별로 고루 잘하는지 편향적으로 잘하는지 알아보기 위해 세과목 점수간 표준편차 사용 
print(person_std)

In [0]:
person_std_list=list(person_std)

In [1]:
i=0
for i in range(len(person_std_list)):
  print("본 피평가자의 전과목 표준편차는", person_std_list[i])
  i=i+1

NameError: ignored

In [0]:
## 전체의 특징을 보여주는 대표값 선정
#전체 구성원의 과목별 평균과 표준편차: high, low, middle을 포괄하는 전체 구성원의 평균적인 과목별 성취도를 알아보기 위해 평균을 사용하고, 구성원간 성취도의 편차가 큰 과목을 파악하기 위해 표준편차를 사용한다. 
total_mean=np.mean(student_scores_total,axis=0)
total_std=np.std(student_scores_total,axis=0)
print(total_mean), print(total_std)

[43.70666667 41.14       41.97333333]
[28.20178403 30.73955758 29.74288636]


(None, None)

In [0]:
print("전체 구성원의 국어 평균은", total_mean[0])
print("전체 구성원의 영어 평균은",total_mean[1])
print("전체 구성원의 수학 평균은",total_mean[2])

print("전체 구성원의 국어 표준편차는", total_std[0])
print("전체 구성원의 영어 표준편차는",total_std[1])
print("전체 구성원의 수학 표준편차는",total_std[2])


전체 구성원의 국어 평균은 43.70666666666666
전체 구성원의 영어 평균은 41.14
전체 구성원의 수학 평균은 41.973333333333336
전체 구성원의 국어 표준편차는 28.201784025522606
전체 구성원의 영어 표준편차는 30.739557576516944
전체 구성원의 수학 표준편차는 29.742886357730804


In [0]:
# 그룹별 과목별 평균, 중간값, 표준편차 

def representative(student_scores_total):
  np.mean(student_scores_total,axis=0)
  np.median(student_scores_total,axis=0)
  np.std(student_scores_total,axis=0)

  mean_kor=np.mean(student_scores_total,axis=0)[0]
  mean_eng=np.mean(student_scores_total,axis=0)[1]
  mean_math=np.mean(student_scores_total,axis=0)[2]

  med_kor=np.median(student_scores_total,axis=0)[0]
  med_eng=np.median(student_scores_total,axis=0)[1]
  med_math=np.median(student_scores_total,axis=0)[2]

  std_kor=np.std(student_scores_total,axis=0)[0]
  std_eng=np.std(student_scores_total,axis=0)[1]
  std_math=np.std(student_scores_total,axis=0)[2]

  matrix=np.matrix([[mean_kor,med_kor,std_kor],[mean_eng,med_eng,std_eng],[mean_math,med_math,std_math]])
  
  print("이 그룹의 국어 평균은", mean_kor)
  print("이 그룹의 국어 중앙값은", med_kor)
  print("이 그룹의 국어 표준편차는", std_kor)

  print("이 그룹의 영어 평균은", mean_eng)
  print("이 그룹의 영어 중앙값은", med_eng)
  print("이 그룹의 영어 표준편차는", std_eng)

  print("이 그룹의 수학 평균은", mean_math)
  print("이 그룹의 수학 중앙값은", med_math)
  print("이 그룹의 수학 표준편차는", std_math)
  print('\n')
  print(matrix)
  return

In [0]:
representative(student_scores_high)     #매트릭스에 키 값을 입력해줄 수 있나?

이 그룹의 국어 평균은 89.73333333333333
이 그룹의 국어 중앙값은 91.0
이 그룹의 국어 표준편차는 5.195724738239657
이 그룹의 영어 평균은 89.3
이 그룹의 영어 중앙값은 89.5
이 그룹의 영어 표준편차는 6.1975801729384665
이 그룹의 수학 평균은 89.06666666666666
이 그룹의 수학 중앙값은 89.0
이 그룹의 수학 표준편차는 6.672996994521194


[[89.73333333 91.          5.19572474]
 [89.3        89.5         6.19758017]
 [89.06666667 89.          6.67299699]]


In [0]:
representative(student_scores_middle)

이 그룹의 국어 평균은 62.2
이 그룹의 국어 중앙값은 64.0
이 그룹의 국어 표준편차는 5.8275209137333865
이 그룹의 영어 평균은 66.2
이 그룹의 영어 중앙값은 69.0
이 그룹의 영어 표준편차는 9.421252570651102
이 그룹의 수학 평균은 65.0
이 그룹의 수학 중앙값은 65.5
이 그룹의 수학 표준편차는 8.264381404557755


[[62.2        64.          5.82752091]
 [66.2        69.          9.42125257]
 [65.         65.5         8.2643814 ]]


In [0]:
representative(student_scores_low)

이 그룹의 국어 평균은 23.14
이 그룹의 국어 중앙값은 22.0
이 그룹의 국어 표준편차는 14.15911014153079
이 그룹의 영어 평균은 24.78
이 그룹의 영어 중앙값은 23.5
이 그룹의 영어 표준편차는 14.497296299655327
이 그룹의 수학 평균은 21.19
이 그룹의 수학 중앙값은 19.5
이 그룹의 수학 표준편차는 13.975474947206623


[[23.14       22.         14.15911014]
 [24.78       23.5        14.4972963 ]
 [21.19       19.5        13.97547495]]


시사점: 각 과목별로 평균이 낮은 집단일수록 집단 내 구성원간 해당 과목의 표준편차가 크게 나타났다. 이러한 특징은 특히 group low에서 두드러지게 나타나고 있는데 평균적인 성취도가 낮은 집단 내에 이상점으로 파악할 만큼 낮은 성취를 보이는 피평가자가 있는 것으로 추론할 수 있다.  